export const mockMovies = {
  popular: {
    page: 1,
    results: [
      {
        id: 1,
        title: "The Shawshank Redemption",
        overview:
          "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        poster_path: "/abstract-movie-poster.png",
        backdrop_path: "/movie-backdrop.png",
        release_date: "1994-09-23",
        vote_average: 9.3,
        vote_count: 2500000,
        genre_ids: [18, 80],
        adult: false,
        original_language: "en",
        original_title: "The Shawshank Redemption",
        popularity: 95.5,
        video: false,
      },
      {
        id: 2,
        title: "The Godfather",
        overview:
          "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        poster_path: "/abstract-movie-poster.png",
        backdrop_path: "/movie-backdrop.png",
        release_date: "1972-03-24",
        vote_average: 9.2,
        vote_count: 1800000,
        genre_ids: [18, 80],
        adult: false,
        original_language: "en",
        original_title: "The Godfather",
        popularity: 92.1,
        video: false,
      },
      {
        id: 3,
        title: "The Dark Knight",
        overview:
          "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
        poster_path: "/abstract-movie-poster.png",
        backdrop_path: "/movie-backdrop.png",
        release_date: "2008-07-18",
        vote_average: 9.0,
        vote_count: 2200000,
        genre_ids: [28, 80, 18],
        adult: false,
        original_language: "en",
        original_title: "The Dark Knight",
        popularity: 88.7,
        video: false,
      },
      {
        id: 4,
        title: "Pulp Fiction",
        overview:
          "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
        poster_path: "/abstract-movie-poster.png",
        backdrop_path: "/movie-backdrop.png",
        release_date: "1994-10-14",
        vote_average: 8.9,
        vote_count: 1900000,
        genre_ids: [80, 18],
        adult: false,
        original_language: "en",
        original_title: "Pulp Fiction",
        popularity: 85.3,
        video: false,
      },
    ],
    total_pages: 500,
    total_results: 10000,
  },
  trending: {
    page: 1,
    results: [
      {
        id: 5,
        title: "Oppenheimer",
        overview:
          "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
        poster_path: "/abstract-movie-poster.png",
        backdrop_path: "/movie-backdrop.png",
        release_date: "2023-07-21",
        vote_average: 8.4,
        vote_count: 850000,
        genre_ids: [18, 36],
        adult: false,
        original_language: "en",
        original_title: "Oppenheimer",
        popularity: 95.8,
        video: false,
      },
      {
        id: 6,
        title: "Barbie",
        overview:
          "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.",
        poster_path: "/abstract-movie-poster.png",
        backdrop_path: "/movie-backdrop.png",
        release_date: "2023-07-21",
        vote_average: 7.2,
        vote_count: 650000,
        genre_ids: [35, 14],
        adult: false,
        original_language: "en",
        original_title: "Barbie",
        popularity: 92.4,
        video: false,
      },
    ],
    total_pages: 1000,
    total_results: 20000,
  },
}

export const mockMovieDetails = {
  1: {
    id: 1,
    title: "The Shawshank Redemption",
    overview:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster_path: "/abstract-movie-poster.png",
    backdrop_path: "/movie-backdrop.png",
    release_date: "1994-09-23",
    vote_average: 9.3,
    vote_count: 2500000,
    runtime: 142,
    genres: [
      { id: 18, name: "Drama" },
      { id: 80, name: "Crime" },
    ],
    production_companies: [{ id: 97, name: "Castle Rock Entertainment" }],
    production_countries: [{ iso_3166_1: "US", name: "United States of America" }],
    spoken_languages: [{ iso_639_1: "en", name: "English" }],
    status: "Released",
    tagline: "Fear can hold you prisoner. Hope can set you free.",
    budget: 25000000,
    revenue: 16000000,
    adult: false,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    popularity: 95.5,
    video: false,
  },
}

export const mockCredits = {
  1: {
    id: 1,
    cast: [
      {
        id: 504,
        name: "Tim Robbins",
        character: "Andy Dufresne",
        profile_path: "/diverse-person-profiles.png",
        order: 0,
      },
      {
        id: 192,
        name: "Morgan Freeman",
        character: "Ellis Boyd 'Red' Redding",
        profile_path: "/diverse-person-profiles.png",
        order: 1,
      },
    ],
    crew: [
      {
        id: 4027,
        name: "Frank Darabont",
        job: "Director",
        department: "Directing",
        profile_path: "/diverse-person-profiles.png",
      },
    ],
  },
}
